# Generated by Django 6.0.3 on 2026-03-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
    ]
